// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:bf055d7f-6339-4004-bcfb-4aa85c2c2dbe",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Gx8cMYi1V",
    "aws_user_pools_web_client_id": "748d9ilpcevci16vsdg3ksnuiu",
    "aws_mobile_analytics_app_id": "0dd55fcfecc64c329ca8963640e8f50b",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_user_files_s3_bucket": "myoutfitappd2ad6d03e4a14c1f9956f3cc1205d928",
    "aws_user_files_s3_bucket_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://t6thxpkk6ff3vik3r2fp2yrq4m.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
